var college = [{
    "id": 0,
    "title": "",
    "Established": "",
    "NIRF": "",
    "Affiliated": "",
    "Courses": "",
    "Level": "",
    "Fees": "",
    "Placement": "",
    "Exams": "",
    "Rating": "",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/No-Image-Placeholder.svg/1665px-No-Image-Placeholder.svg.png"
}, {
    "id": 1,
    "title": "IIT Roorkee",
    "Established": 1847,
    "NIRF": "6th ",
    "Affiliated": " UGC,AICTE ",
    "Courses": "23 ",
    "Level": "UG,PG,PhD  ",
    "Fees": "4.16lac/annum ",
    "Placement": "26LPA ",
    "Exams": "IIT-JEE,GATE ",
    "Rating": "4.4/5 ",
    "image": "./img/img1.png",
}, {
    "id": 2,
    "title": "IIT Patna",
    "Established": 2008,
    "NIRF": "33rd",
    "Affiliated": "UGC,AICTE ",
    "Courses": "20 ",
    "Level": "UG,PG,PhD ",
    "Fees": "2.64lac/annum ",
    "Placement": "17.13LPA ",
    "Exams": "IIT-JEE,GATE ",
    "Rating": "8.6/10 ",
    "image": "./img/img2.png",
}, {
    "id": 3,
    "title": "IIT Kharagpur",
    "Established": 179999,
    "NIRF": "Samsung Galaxy S22 price in Pakistan is Rs. 179,999. Official dealers and warranty providers regulate the retail price of Samsung mobile products in official warranty.",
    "Affiliated": "Samsung ",
    "Courses": "Samsung ",
    "Level": "Samsung ",
    "Fees": "Samsung ",
    "Placement": "Samsung ",
    "Exams": "Samsung ",
    "Rating": "Samsung ",
    "image": "./img/img3.png",
}, {
    "id": 4,
    "title": "IIT Guwahati",
    "Established": 179999,
    "NIRF": "Samsung Galaxy S22 price in Pakistan is Rs. 179,999. Official dealers and warranty providers regulate the retail price of Samsung mobile products in official warranty.",
    "Affiliated": "Samsung ",
    "Courses": "Samsung ",
    "Level": "Samsung ",
    "Fees": "Samsung ",
    "Placement": "Samsung ",
    "Exams": "Samsung ",
    "Rating": "Samsung ",
    "image": "./img/img4.png",
}, {
    "id": 5,
    "title": "IIT Bhubaneshwar",
    "Established": 179999,
    "NIRF": "Samsung Galaxy S22 price in Pakistan is Rs. 179,999. Official dealers and warranty providers regulate the retail price of Samsung mobile products in official warranty.",
    "Affiliated": "Samsung ",
    "Courses": "Samsung ",
    "Level": "Samsung ",
    "Fees": "Samsung ",
    "Placement": "Samsung ",
    "Exams": "Samsung ",
    "Rating": "Samsung ",
    "image": "./img/img5.jpg",
}, {
    "id": 6,
    "title": "CV Raman Global University",
    "Established": 179999,
    "NIRF": "Samsung Galaxy S22 price in Pakistan is Rs. 179,999. Official dealers and warranty providers regulate the retail price of Samsung mobile products in official warranty.",
    "Affiliated": "Samsung ",
    "Courses": "Samsung ",
    "Level": "Samsung ",
    "Fees": "Samsung ",
    "Placement": "Samsung ",
    "Exams": "Samsung ",
    "Rating": "Samsung ",
    "image": "./img/img6.png",
}, {
    "id": 7,
    "title": "IIT Madras",
    "Established": 179999,
    "NIRF": "Samsung Galaxy S22 price in Pakistan is Rs. 179,999. Official dealers and warranty providers regulate the retail price of Samsung mobile products in official warranty.",
    "Affiliated": "Samsung ",
    "Courses": "Samsung ",
    "Level": "Samsung ",
    "Fees": "Samsung ",
    "Placement": "Samsung ",
    "Exams": "Samsung ",
    "Rating": "Samsung ",
    "image": "./img/img7.png",
}, {
    "id": 8,
    "title": "NIT Rourkela",
    "Established": 179999,
    "NIRF": "Samsung Galaxy S22 price in Pakistan is Rs. 179,999. Official dealers and warranty providers regulate the retail price of Samsung mobile products in official warranty.",
    "Affiliated": "Samsung ",
    "Courses": "Samsung ",
    "Level": "Samsung ",
    "Fees": "Samsung ",
    "Placement": "Samsung ",
    "Exams": "Samsung ",
    "Rating": "Samsung ",
    "image": "./img/img8.png",
}, {
    "id": 9,
    "title": "NIT Patna",
    "Established": 179999,
    "NIRF": "Samsung Galaxy S22 price in Pakistan is Rs. 179,999. Official dealers and warranty providers regulate the retail price of Samsung mobile products in official warranty.",
    "Affiliated": "Samsung ",
    "Courses": "Samsung ",
    "Level": "Samsung ",
    "Fees": "Samsung ",
    "Placement": "Samsung ",
    "Exams": "Samsung ",
    "Rating": "Samsung ",
    "image": "./img/img9.jfif",
}, {
    "id": 10,
    "title": "NIT Trichy",
    "Established": 179999,
    "NIRF": "Samsung Galaxy S22 price in Pakistan is Rs. 179,999. Official dealers and warranty providers regulate the retail price of Samsung mobile products in official warranty.",
    "Affiliated": "Samsung ",
    "Courses": "Samsung ",
    "Level": "Samsung ",
    "Fees": "Samsung ",
    "Placement": "Samsung ",
    "Exams": "Samsung ",
    "Rating": "Samsung ",
    "image": "./img/img10.jfif",
}]